### ISSUE TITLE
README feedback

### ISSUE THREAD

**Issue by TimDSylvester** [houmain/gpupad#6]
Using MacOS Ventura (13.1) with Homebrew, I had the following minor build issues:

Although the README says "... Qt5 (or Qt6) are required", I got the error:

> /gpupad/src/VideoPlayer.h:6:10: fatal error: 'QAbstractVideoSurface' file not found

Per [the Qt6 docs](https://doc.qt.io/qt-6/qtmultimedia-changes-qt6.html):

> QAbstractVideoSurface has been replaced by the QVideoSink class

I was able to fix this by installing Qt5 with `brew install qt@5`.

Further, it says "you might have to pass the path to your Qt installation", but the command there lists the wrong step, running the makefiles rather than creating them, and should be:

> cmake -B _build -DCMAKE_PREFIX_PATH=C:\Qt\5.15\msvc2019_64

or, in my case:

> cmake -B _build -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5

And this also required clearing the build cache (e.g., deleting `_build`)

You might also mention that `glslangValidator` needs to be installed (`brew install glslang`) before the configure step for it to be found.

**Comment by houmain** [comment]
Thank you very much for your feedback! 
Glad to hear that you got it running on macOS. The CMake script can already generate .dmg packages, but they do not contain the Qt libraries. I guess I need to get my hands on an Apple device one day to finish this...

Now it should be easier so select the Qt version, without clearing the build cache (by setting QT_VERSION_MAJOR).
I fixed the video support with Qt6 (and removed support with Qt5) and updated the README.
Installing the glslangValidator after building should work, since it is an optional runtime dependency (I tested it).

**Comment by TimDSylvester** [comment]
Cool, thanks!

On further testing, the validator error occurs when I run by double-clicking from Finder, but not when I run with `open _build/gpupad.app`.  I suspect that `glslangValidator` is only in the PATH due to something in `.bash_profile`, and so isn't found except in the context of a terminal.
